document: feedback-pipeline-workload
version: 1
data:
  name: python-pam
  description: Python bindings for libpam.
  maintainer: sst_idm_sssd
  packages:
    - python3-pam
  labels:
    - eln
    - c10s
